### ISSUE TITLE
[BUG] libtorrent is missing

### ISSUE THREAD

**Issue by erichlf** [linuxserver/docker-flexget#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

libtorrent appears to me missing

### Expected Behavior

No error message relating to libtorrent

### Steps To Reproduce

1. Using a container newer than [v3.11.37-ls101](https://github.com/linuxserver/docker-flexget/releases/tag/v3.11.37-ls101)
2. Run the container
3. Using a config that requires torrent interaction 

### Environment

```markdown
- OS: QNAP
- How docker service was installed: qpkg
```

### CPU architecture

x86-64

### Docker creation

```bash
I used portainer and docker compose to create the container.
```

### Container logs

```bash
"CRITICAL task          TV              libtorrent package required"
```

**Comment by thespad** [comment]
I suspect you're running into a variant of https://info.linuxserver.io/issues/2023-05-22-portainer/ as I can't replicate this, certainly not without the actual config elements that you're using to generate the error.

**Comment by erichlf** [comment]
I'm not on Synology, but this container was broken when i first created it. I had to change the image version until I found one that worked. In the container itself running
```
pip install libtorrent
```
gives the error
> ERROR: Could not find a version that satisfies the requirement libtorrent (from versions: none)
ERROR: No matching distribution found for libtorrent

To replicate it seems that all you need is to attempt to connect to qbitorrent. Don't actually need to connect to it. You can see my config here: https://github.com/erichlf/flexget

**Comment by thespad** [comment]
It will, there's no compatible libtorrent package available on pypi. And that issue is not specific to Synology.

I still can't replicate the issue, however, whatever I try I can't get it to throw that libtorrent error.

Please run `docker exec flexget ls -la /lsiopy/lib/python3.12/site-packages/libtorrent.cpython-312-x86_64-linux-musl.so` from the host and provide the output.

**Comment by erichlf** [comment]
That is interesting:
```
-rwxr-xr-x 1 root root 5080568 May 23 04:38 /lsiopy/lib/python3.12/site-packages/libtorrent.cpython-312-x86_64-linux-musl.so
```

**Comment by thespad** [comment]
OK, what's the output from `docker exec flexget cat /run/s6/container_environment/PATH` ?

**Comment by erichlf** [comment]
> /command:/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

**Comment by thespad** [comment]
OK so your path is correct and the lib is in the right place, so I'm not sure why it can't find it.

**Comment by erichlf** [comment]
I rebuilt not using protainer and it works, so it does appear to be caused by portainer.

**Comment by j0nnymoe** [comment]
Glad you've got it working but also just to note, the article spad linked earlier clearly shows it's a synology and portainer bug.
