### ISSUE TITLE
[BUG] permission of svc-flexget

### ISSUE THREAD

**Issue by christaikobo** [linuxserver/docker-flexget#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The directory `svc-flexget` belongs to root user and group, and flexget is run by user `abc` with whatever uid and gid the user specifies using env. 

Some of the plugins of flexget will try to write temporary files to `$cwd` which is `svc-flexget`, and it sounds reasonable to me, but they obviously lack the permission to do so, resulting in errors.

I wonder, if it is possible to set the owner and group of svc-flexget to be `abc` instead of `root`?

### Steps To Reproduce

Run docker-flexget, use plugins like flexget_qbittorrent_mod

### Environment

```markdown
- OS: Synology
- How docker service was installed: Synology store
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
  --name flexget \
  --hostname flexget \
  -e FG_WEBUI_PASSWORD=sadgdgsF42365632rAyag8qdq \
  -e FG_LOG_LEVEL=info \
  -e FG_LOG_FILE=/config/log/flexget.log \
  -e FG_CONFIG_FILE=/config/config.yml \
  -e PUID=1026 \
  -e PGID=101 \
  -v *****:/data \
  -v *****:/config \
  ghcr.io/linuxserver/flexget
```

### Container logs

```bash
Everything normal except permission denied for the creation of a temporary file in svc-flexget.
```

**Comment by thespad** [comment]
No, it's not possible to change the folder ownership, but there shouldn't be any issue with changing the working directory. I'll take a look at it.
